# Load distro-specific variables
# Hard pull in parrot first, due to parrot's distribution name including a "/" which breaks file naming. Can possibly fix this in the Startup.sh? Need to regex change /etc/os-release
- include_vars: 'parrot.yml'
  tags: always

- include_vars: '{{ ansible_distribution }}.yml'
  tags: always

- block:
    # - import_tasks: nrpe.yml
    # - import_tasks: ufw.yml
    # - import_tasks: qemu-agent.yml

    # - include_tasks: unattended_upgrades.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true

  rescue:
    - set_fact: task_failed=true
