---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/upgrade.yml
    - include: tasks/packages.yml
    - include: tasks/bash.yml
    - include: tasks/tmux.yml    