---
- hosts: localhost
  connection: local
  tags: always
  become: true

  pre_task:
    - name: update repo
     tags: always
     package: 
       update_cache: yes
     change_when: False

  tasks:
  - name: install Packages
    package:
      name: 
        - htop
        - tmux
        - net-tools
        - git
        - curl
        - wget
      state: latest

#run roles
#- hosts: all
#  tags:
  


