---
- hosts: localhost
  connection: local
  tags: always
  become: true
  pre_task:
    -name: update repo
     tags: always
     apt: update_cache=yes
     change_when: False

  tasks:
  - name: install htop
    package:
      name: htop

#run roles
#- hosts: all
#  tags:
  


