--- 
- 
  hosts: localhost
  connection: local
  become: true
  pre_task: 
    - 
      name: "update repo"
      package: 
        update_cache: true

  tasks: 
    - 
      name: "install Packages"
      package: 
        name: 
          - htop
          - tmux
          - net-tools
          - git
          - curl
          - wget
        
