--- 
- 
  become: true
  connection: local
  hosts: localhost
  pre_task: 
    - 
      change_when: false
      name: "update repo"
      package: 
        update_cache: true
  tasks: 
    - 
      name: "install Packages"
      package: 
        name: 
          - htop
          - tmux
          - net-tools
          - git
          - curl
          - wget
        state: latest
