---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/packages.yml
    - include: tasks/bash.yml
    - include: tasks/tmux.yml
    - include: tasks/lesbian.yml
    - include: tasks/unattended_upgrades.yml
    - include: tasks/wallpaper.yml
    #- include: Keyboard_layout.yml
    #- include: tasks/cron.yml
    