- include_vars: vars_user.yml

# copy current bashrc to .bak 
- name: backup bashrc
  become_user: freaky
  copy:
    src: /home/freaky/.bashrc
    dest: /home/freaky/.bashrc.bak

# copy new copy of bashrc
- name: copy bashrc file
  become_user: freaky
  copy:
    src: files/bashrc
    dest: /home/freaky/.bashrc
    owner: freaky
    group: freaky

# copy new copy of bash aliases
- name: copy bash aliases file
  become_user: freaky
  copy:
    src: files/bash_aliases
    dest: /home/freaky/.bash_aliases
    owner: freaky
    group: freaky