- name: backup bashrc
  copy:
    src: /home/freaky/.bashrc
    dest: /home/freaky/.bashrc.bak

- name: copy bashrc file
  copy:
    src: files/bashrc
    dest: /home/freaky/.bashrc
    owner: freaky
    group: freaky

