- include_vars: vars_user.yml

- name: set favorite list
  set_fact:
    favorite_apps:
      - firefox_firefox.desktop
      - org.gnome.Nautilus.desktop
      - code.desktop
      - org.gnome.Terminal.desktop
      - discord.desktop

# set favorite on side bar
- name: change favorites
  tags: favorites
  become_user: "{{main_user}}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "[{% for item in favorite_apps %}('{{ item }}'),{% endfor %}]"
    state: present
