---
- name: Check if my_package is installed
  command: dpkg-query -W my_package
  register: my_package_check_deb
  failed_when: my_package_check_deb.rc > 1
  changed_when: my_package_check_deb.rc == 1
 
- name: Download my_package
  become_user: freaky
  get_url: 
    url="{{https://discord.com/api/download?platform=linux&format=deb}}"
    dest="/home/freaky/Downloads/{{ my_package_name }}.deb"
  when: my_package_check_deb.rc == 1

- name: Install my_package
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/{{ my_package_name }}.deb"
  sudo: true
  when: my_package_check_deb.rc == 1