- name: users | lesbian | create group
  tags: groups,lesbian,users
  group:
    name: lesbian
    state: present

- name: users | lesbian | create user
  tags: lesbian,sudo,users
  user:
    name: lesbian
    group: lesbian
    state: present
    comment: "ansible User"
    
- name: users | lesbian | add sudoers file
  tags: settings,lesbian,sudo,system,users
  copy:
    src: users/sudoers_lesbian
    dest: /etc/sudoers.d/lesbian
    owner: root
    group: root
    mode: 0440


- name: users | lesbian | create .ssh directory
  tags: dotfiles,lesbian,ssh,users
  file:
    path: /home/lesbian/.ssh
    state: directory
    owner: lesbian
    group: lesbian
    mode: 0700
  

- name: add ssh key for User ansible
  tags: always
  authorized_key:
    user: lesbian
    state: present
    key: "{{lookup ('file','/home/lesbian/.ssh/ansible_client_ed25519.pub')}}"