- name: users | lesbian | create group
  group:
    name: lesbian
    state: present

- name: users | lesbian | create user
  user:
    name: lesbian
    group: lesbian
    groups: lesbian, root
    state: present
    comment: "ansible User"
    
- name: users | lesbian | add sudoers file
  become: true
  copy:
    src: sudoers_lesbian
    dest: /etc/sudoers.d/lesbian
    owner: root
    group: root
    mode: 0440


- name: users | lesbian | create .ssh directory
  file:
    path: /home/lesbian/.ssh
    state: directory
    owner: lesbian
    group: lesbian
    mode: 0700
  

- name: add ssh key for User ansible
  become_user: lesbian
  authorized_key:
    user: lesbian
    state: present
    key: ssh-ed25519 AAAC3NzaC1lZDI1NTE5AAAAIBlslg0lTqwWwNgyhRDreBKP6NjSI5ewt7YTDzsa2nTe Ansible