- name: dev packages
  tags: dev
  package:
    name:
      - git
      - perl
      - tig
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_virtualenv_package }}"
      - "{{ python_psutil_package }}"
    state: latest
    