- name: cleanup packages remove unneeded packages...
  tags: cleanup
  become: true
  package:
    name:
      - cowsay
      - vim
      - exim4
      - exim4-base
      - exim4-config
    state: absent
    when: ansible_distrubution in ["Debian", "Ubuntu"]