- name: set terminal color
  dconf:
    key: "org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9"
    value: "background-color='rgb(0,0,0)'"
- name: set terminal color foreground
  dconf:
    key: "org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9"
    value: "foreground-color='rgb(0,255,0)'"
- name: set terminal color background
  dconf:
    key: "org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9"
    value: "'use-theme-colors=false'"

#[org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
#background-color='rgb(0,0,0)'
#foreground-color='rgb(0,255,0)'
#use-theme-colors=false