- name: some variables
  vars: 
    vscode_ppa: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    vscode_ppa_key: https://packages.microsoft.com/keys/microsoft.asc
    vscode_ppa_id: BE1229CF

- name: add vscode repo
  apt_repository: repo="{{ vscode_ppa }}" state=present
  sudo: true

- name: add public key
  apt_key: url="{{ vscode_ppa_key }}" id="{{ vscode_ppa_id }}" state=present
  sudo: true

- name: update cache
  apt: update_cache=yes
  sudo: true

- name: install vscode
  apt: pkg="{{ item }}" state=latest
  with_items:
    - code
  sudo: true