---


# Repository for Visual Studio Code

- name: Add repository key for Visual Studio Code
  apt_key: 
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: true
  tags:
    - repo
    - vscode

- name: Add repository for Visual Studio Code
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
  become: true
  tags:
    - repo
    - vscode

- name: "refresh apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - repo

# Install Visual Studio Code

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
  become: true
  tags:
    - vscode