- name: copy wallpaper file
  copy:
    src: Wallpaper/Angela Gossow.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root

- name: set wallpaper
  become_user: freaky
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: freaky
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
## Lock Screen Wallpaper not working in gnome 3.36
- name: Copy lockscreenfile
  copy: 
    src: Wallpaper/Metal name.jpg 
    dest: /usr/share/backgrounds/ansible-lockscreen.jpg 
    owner: root 
    group: root

- name: Set lock screen background
  become_user: freaky
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" 
    value="'file:///usr/share/backgrounds/ansible-lockscreen.jpg'"
