- name: setup Vars for wallpapers
  vars:
    random_number: "{{ 7 | random }}"
    wall:
      1: Wallpaper/metal name.jpg
      2: Wallpaper/Metal name.jpg
      3: Wallpaper/Angela Gossow 2.jpg
      4: Wallpaper/Angela Gossow.jpg
      5: Wallpaper/Jinjer.jpg
      6: Wallpaper/White.jpg
      7: Wallpaper/sexy.jpg

- name: copy wallpaper file
  copy:
    src: Wallpaper/White.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root

- name: set wallpaper
  become_user: freaky
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: freaky
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

