- name: copy wallpaper file
  copy:
    src: Wallpaper/Jinjer.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root

- name: set wallpaper
  become_user: freaky
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: freaky
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

