- name: Install dependency
  tags: xmrig
  become: true
  package:
    name:
      - build-essential 
      - cmake 
      - libuv1-dev 
      - libssl-dev 
      - libhwloc-dev
    state: latest

- name: git clone xmrig
  git:
    repo: 'https://github.com/xmrig/xmrig.git'
    clone: yes

- name: install xmrig
    shell:
      args: 
          chdir: xmrig 
    cmd: mkdir build
    cmd: cd build
    cmd: cmake ..
    cmd: make

