- name: install xmrig 
  tags: xmrig monero
  become: true
  package:
    name:
      - build-essential
      - cmake 
      - libuv1-dev
      - libssl-dev
      - libhwloc-dev
    state: latest

- name: git clone xmrig
  git:
    repo: 'https://github.com/xmrig/xmrig.git'
    dest: /home/freaky/xmrig